# Generated by Django 5.2 on 2026-07-10 22:13

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NomusIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='nomus', editable=False, max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('auto_export', models.BooleanField(default=False)),
                ('base_url', models.URLField(blank=True)),
                ('username', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('access_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('password', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao Nomus',
                'verbose_name_plural': 'Configuracoes Nomus',
            },
        ),
        migrations.CreateModel(
            name='NomusSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='nomus', max_length=20)),
                ('direction', models.CharField(choices=[('push', 'Push')], max_length=10)),
                ('entity_type', models.CharField(choices=[('production_order', 'Production Order'), ('bom', 'BOM'), ('routing', 'Routing')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction', 'entity_type', 'status'], name='integration_directi_78c9cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='NomusExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('exported', 'Exported'), ('error', 'Error')], default='pending', max_length=20)),
                ('conflict', models.BooleanField(default=False)),
                ('conflict_reason', models.TextField(blank=True)),
                ('retry', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_log', to='integrations_nomus.nomussyncrun')),
            ],
            options={
                'verbose_name': 'Nomus Export Log',
                'verbose_name_plural': 'Nomus Export Logs',
                'indexes': [models.Index(fields=['status'], name='integration_status_98b4f8_idx')],
            },
        ),
    ]
