# Generated by Django 5.2 on 2026-06-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('intro_template', models.TextField(default='Prezados, apresentamos nossa proposta para fornecimento de {{ titulo }}, conforme especificações técnicas a seguir.')),
                ('scope_template', models.TextField(default='Escopo: {{ escopo }} — {{ n_tubos }} tubos {{ tubo_material }} {{ tubo_od }} x {{ tubo_parede }}, {{ tubo_comp_mm }} mm.')),
                ('terms_template', models.TextField(default='Prazo de entrega: {{ delivery_weeks }} semanas. Validade da proposta: {{ validity_days }} dias. Condições de pagamento: {{ payment_terms }}.')),
                ('closing_template', models.TextField(default='Permanecemos à disposição para esclarecimentos.\nAtenciosamente,\n{{ empresa }}.')),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('delivery_weeks', models.PositiveIntegerField(default=8)),
                ('payment_terms', models.CharField(default='30 dias da entrega', max_length=255)),
                ('company_name', models.CharField(default='ENGEMATEX', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta'), ('sent', 'Enviada'), ('superseded', 'Substituída')], default='draft', max_length=20)),
                ('intro_text', models.TextField(blank=True)),
                ('scope_text', models.TextField(blank=True)),
                ('terms_text', models.TextField(blank=True)),
                ('closing_text', models.TextField(blank=True)),
                ('docx_path', models.CharField(blank=True, max_length=500)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('docx_sha256', models.CharField(blank=True, max_length=64)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='quotations.quotation')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.proposaltemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
