# Generated by Django 5.2 on 2026-07-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='exclusions_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='object_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='exclusions_template',
            field=models.TextField(default='Não estão incluídos no fornecimento: frete e transporte, montagem em campo, obras civis, isolamento térmico, pintura externa e testes não destrutivos além dos especificados — salvo indicação expressa em contrário.'),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='object_template',
            field=models.TextField(default='Fornecimento de {{ titulo }} para {{ cliente }}, conforme especificações técnicas, memorial de cálculo e composição de preço a seguir.'),
        ),
    ]
