# Generated by Django 5.2 on 2026-07-07 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proposals", "0002_proposal_exclusions_text_proposal_object_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.PositiveIntegerField()),
                ("number", models.CharField(max_length=100)),
                ("pdf_path", models.CharField(max_length=500)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("email_to", models.EmailField(blank=True, max_length=254)),
                (
                    "emailed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emailed_proposal_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_proposal_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number", "-generated_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="proposalversion",
            constraint=models.UniqueConstraint(fields=("proposal", "version_number"), name="uniq_proposal_version_number"),
        ),
    ]
