# Generated by Django 5.2 on 2026-06-23 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0002_calculationsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OFItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('custo_material', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_mo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('source_item_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'codigo_item'],
            },
        ),
        migrations.CreateModel(
            name='OFMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mp', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=50)),
                ('forma', models.CharField(max_length=20)),
                ('peso_bruto_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_liquido_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('preco_kgf', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='production.ofitem')),
            ],
        ),
        migrations.CreateModel(
            name='OFOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_op', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=20)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('aplicavel', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='production.ofitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemFabricacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('quotation_number', models.CharField(max_length=50)),
                ('quotation_revision', models.PositiveSmallIntegerField(default=0)),
                ('snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('customer_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('scope', models.CharField(choices=[('tube_bundle', 'Feixe Tubular'), ('complete', 'Equipamento Completo')], max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('liberada', 'Liberada'), ('em_producao', 'Em Produção'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('custo_material', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_mo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('preco_com_impostos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('peso_bruto_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_liquido_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('calculation_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_fabricacao', to='quotations.calculationsnapshot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_fabricacao', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_fabricacao', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ofitem',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='production.ordemfabricacao'),
        ),
        migrations.AddIndex(
            model_name='ordemfabricacao',
            index=models.Index(fields=['status', 'created_at'], name='production__status_bfb520_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemfabricacao',
            index=models.Index(fields=['quotation', 'created_at'], name='production__quotati_e84fbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordemfabricacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelada'), _negated=True), fields=('quotation',), name='uniq_active_of_per_quotation'),
        ),
    ]
