# Generated by Django 5.2 on 2026-06-23 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemfabricacao',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofs_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemfabricacao',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofs_concluidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemfabricacao',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofs_liberadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemfabricacao',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofs_iniciadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
