# Generated by Django 5.2 on 2026-06-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_ordemfabricacao_cancelled_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_hh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hours_hm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('entry_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('of_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='production.ofoperation')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['of_operation', 'entry_date'], name='production__of_oper_089f8d_idx')],
            },
        ),
    ]
