# Generated by Django 5.2 on 2026-06-23 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(max_length=100, unique=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('mean_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('m2', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(db_index=True, max_length=100)),
                ('estimated_custo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_hh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observed_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('of_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='production.ofoperation')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='production.ordemfabricacao')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['operacao', 'observed_at'], name='production__operaca_089287_idx')],
            },
        ),
    ]
