# Generated by Django 5.2 on 2026-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_actualrate_productionobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualrate',
            name='mean_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14),
        ),
    ]
