# Generated by Django 5.2 on 2026-06-24 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_actualrate_mean_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('source_operations_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('completed', 'Concluído')], default='open', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_plans_generated', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_plan', to='production.ordemfabricacao')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('codigo_item', models.CharField(max_length=30)),
                ('item_descricao', models.CharField(max_length=255)),
                ('codigo_op', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=20)),
                ('inspection_type', models.CharField(default='processo', max_length=30)),
                ('criterio', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_items_accepted', to=settings.AUTH_USER_MODEL)),
                ('of_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_items', to='production.ofoperation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.inspectionplan')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['plan', 'status', 'sequence'], name='production__plan_id_62b3ac_idx'), models.Index(fields=['of_operation'], name='production__of_oper_317bb0_idx')],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('of_operation__isnull', False)), fields=('plan', 'of_operation'), name='uniq_itp_item_per_operation'),
                    models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('accepted_by__isnull', True), ('status', 'pending')), models.Q(('accepted_at__isnull', False), ('accepted_by__isnull', False), ('status', 'accepted')), _connector='OR'), name='ck_itp_item_acceptance_consistent'),
                ],
            },
        ),
    ]
