# Generated by Django 5.2 on 2026-07-10 16:46

from decimal import Decimal
from django.db import migrations, models


def backfill_ofoperation_cost_fields(apps, schema_editor):
    OFOperation = apps.get_model("production", "OFOperation")
    OFOperation.objects.all().update(
        custo_direto=True,
        horas_hh=0,
        horas_hm=0,
        taxa_hora=0,
        taxa_hora_hm=0,
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_inspectionplan_inspectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofoperation',
            name='custo_direto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ofoperation',
            name='horas_hh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ofoperation',
            name='horas_hm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='ofoperation',
            name='taxa_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ofoperation',
            name='taxa_hora_hm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_ofoperation_cost_fields, noop_reverse),
    ]
