# Generated by Django 5.2 on 2026-07-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_ofoperation_custo_direto_ofoperation_horas_hh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionobservation',
            name='delta_horas_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(actual_hh − estimated_hh) / estimated_hh × 100. Null quando estimated_hh=0 (operação de valor fixo, sem horas estimadas) — evita divisão por zero.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productionobservation',
            name='estimated_hh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
