# Generated by Django 5.2 on 2026-06-05 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantParamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator_correcao_mo', models.DecimalField(decimal_places=4, default=1.0, max_digits=6)),
                ('drill_method_threshold_holes', models.IntegerField(default=600)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant param config',
                'verbose_name_plural': 'Tenant param config',
            },
        ),
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(db_index=True, max_length=100)),
                ('metodo', models.CharField(choices=[('radial', 'Radial'), ('cnc', 'CNC'), ('manual', 'Manual')], max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unidade', models.CharField(choices=[('mm/min', 'mm/min'), ('min/furo', 'min/furo'), ('min/tubo', 'min/tubo'), ('juntas/h', 'juntas/h'), ('tubos/h', 'tubos/h'), ('fator', 'fator')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['operacao', 'metodo', '-valid_from'],
                'indexes': [models.Index(fields=['operacao', 'metodo', 'valid_from'], name='engineering_operaca_c5e797_idx')],
                'constraints': [models.UniqueConstraint(fields=('operacao', 'metodo', 'valid_from'), name='uniq_processparam_op_metodo_valid_from')],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(db_index=True, max_length=100)),
                ('rate_hh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_hm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['operacao', '-valid_from'],
                'indexes': [models.Index(fields=['operacao', 'valid_from'], name='engineering_operaca_362898_idx')],
                'constraints': [models.UniqueConstraint(fields=('operacao', 'valid_from'), name='uniq_rate_operacao_valid_from')],
            },
        ),
    ]
