# Generated by Django 5.2 on 2026-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_params', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantparamconfig',
            name='tema_compat_mode',
            field=models.CharField(choices=[('block', 'Bloquear'), ('warn', 'Avisar'), ('free', 'Livre')], default='warn', max_length=10),
        ),
    ]
