# Generated by Django 5.2 on 2026-06-23 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_params', '0002_tenantparamconfig_tema_compat_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(db_index=True, max_length=100)),
                ('actual_mean_rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('current_rate_hh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delta_pct', models.DecimalField(decimal_places=2, max_digits=7)),
                ('n_samples', models.PositiveIntegerField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aplicada'), ('dismissed', 'Descartada')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('operacao',), name='uniq_suggestion_pending_por_operacao')],
            },
        ),
    ]
