# Generated by Django 5.2 on 2026-07-18 01:04

import apps.engineering_params.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_params', '0004_processparameter_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantparamconfig',
            name='baffle_cut_default_pct',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenantparamconfig',
            name='tube_standard_lengths_mm',
            field=models.JSONField(default=apps.engineering_params.models._default_tube_standard_lengths),
        ),
        migrations.AddField(
            model_name='tenantparamconfig',
            name='u_bend_min_radius_factor',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
    ]
