# Generated by Django 5.2 on 2026-07-18 18:09

import apps.engineering_params.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_params', '0005_tenantparamconfig_baffle_cut_default_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantparamconfig',
            name='perda_por_familia',
            field=models.JSONField(default=apps.engineering_params.models._default_perda_por_familia),
        ),
        migrations.AddField(
            model_name='tenantparamconfig',
            name='setup_frac',
            field=models.JSONField(default=apps.engineering_params.models._default_setup_frac),
        ),
    ]
