# Generated by Django 5.2.17 on 2026-09-28 07:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_params', '0007_knobchangeproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantparamconfig',
            name='fator_preco_completo',
            field=models.DecimalField(decimal_places=5, default=Decimal('1.25'), max_digits=8),
        ),
        migrations.AddField(
            model_name='tenantparamconfig',
            name='impostos_pct_completo',
            field=models.DecimalField(decimal_places=3, default=Decimal('9.0'), max_digits=6),
        ),
    ]
