# Generated by Django 5.2 on 2026-06-22 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('quotations', '0002_calculationsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('generate', 'Generate'), ('approve', 'Approve'), ('revoke', 'Revoke')], max_length=20)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'resource_type', 'created_at'], name='audit_acces_action_79e5eb_idx'), models.Index(fields=['user', 'created_at'], name='audit_acces_user_id_661590_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crea_number', models.CharField(max_length=50)),
                ('crea_state', models.CharField(blank=True, max_length=2)),
                ('art_number', models.CharField(blank=True, max_length=100)),
                ('calculation_snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_approvals', to='accounts.userprofile')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_approvals', to='quotations.quotation')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_technical_approvals', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-approved_at'],
                'indexes': [models.Index(fields=['quotation', 'approved_at'], name='audit_techn_quotati_89b2de_idx')],
            },
        ),
    ]
