# Generated by Django 5.2 on 2026-06-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_accesslog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('generate', 'Generate'), ('approve', 'Approve'), ('revoke', 'Revoke'), ('convert', 'Convert'), ('transition', 'Transition'), ('appoint', 'Appoint')], max_length=20),
        ),
    ]
