# Generated by Django 5.2 on 2026-07-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("quotations", "0003_customer_phone"),
        ("audit", "0004_alter_accesslog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_type", models.CharField(choices=[("remote", "Remota"), ("presential", "Presencial")], default="remote", max_length=20)),
                ("snapshot_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("approved", "Aprovada"), ("cancelled", "Cancelada")], db_index=True, default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("quotation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approval_requests", to="quotations.quotation")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approval_requests", to="accounts.userprofile")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["quotation", "status", "created_at"], name="audit_appro_quotati_cf2b6b_idx")],
            },
        ),
    ]
