# Generated by Django 5.2 on 2026-07-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_accesslog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('generate', 'Generate'), ('approve', 'Approve'), ('revoke', 'Revoke'), ('convert', 'Convert'), ('transition', 'Transition'), ('appoint', 'Appoint'), ('itp_generate', 'ITP Generate'), ('itp_accept', 'ITP Accept'), ('edit', 'Edit'), ('rate_change', 'Rate Change')], max_length=20),
        ),
    ]
