# Generated by Django 5.2 on 2026-07-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_roles'),
        ('audit', '0011_alter_accesslog_action'),
        ('quotations', '0008_quotation_pricing_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('generate', 'Generate'), ('approve', 'Approve'), ('revoke', 'Revoke'), ('convert', 'Convert'), ('transition', 'Transition'), ('appoint', 'Appoint'), ('itp_generate', 'ITP Generate'), ('itp_accept', 'ITP Accept'), ('edit', 'Edit'), ('rate_change', 'Rate Change'), ('param_change', 'Param Change'), ('role_change', 'Role Change'), ('member_deactivate', 'Member Deactivate'), ('permission_change', 'Permission Change'), ('approval_config_change', 'Approval Config Change'), ('case_open', 'Approval Case Open'), ('task_approve', 'Approval Task Approve'), ('task_reject', 'Approval Task Reject'), ('case_invalidate', 'Approval Case Invalidate')], max_length=32),
        ),
        migrations.CreateModel(
            name='ApprovalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(default='of.convert', max_length=32)),
                ('workflow_snapshot', models.JSONField(default=list)),
                ('snapshot_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('completed', 'Concluído'), ('rejected', 'Rejeitado'), ('invalidated', 'Invalidado')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_cases', to='quotations.quotation')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_cases_requested', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(max_length=64)),
                ('stage_label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('required', models.BooleanField(default=True)),
                ('approver_capability', models.CharField(blank=True, max_length=64)),
                ('is_builtin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('skipped', 'Pulada'), ('invalidated', 'Invalidada')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='audit.approvalcase')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.userprofile')),
                ('technical_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='audit.technicalapproval')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalcase',
            index=models.Index(fields=['quotation', 'status', 'created_at'], name='audit_appro_quotati_f002ce_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['case', 'status', 'order'], name='audit_appro_case_id_adf013_idx'),
        ),
    ]
