# Generated by Django 5.2 on 2026-06-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_sap_b1', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sapb1syncbinding',
            new_name='integration_entity__6047cd_idx',
            old_name='sap_b1_bind_local_idx',
        ),
        migrations.RenameIndex(
            model_name='sapb1syncbinding',
            new_name='integration_entity__de58d5_idx',
            old_name='sap_b1_bind_remote_idx',
        ),
        migrations.RenameIndex(
            model_name='sapb1syncrun',
            new_name='integration_directi_104a6f_idx',
            old_name='sap_b1_run_dir_ent_sta_idx',
        ),
        migrations.RenameIndex(
            model_name='sapb1syncrun',
            new_name='integration_local_m_f0b472_idx',
            old_name='sap_b1_run_local_idx',
        ),
    ]
