# Generated by Django 5.2 on 2026-06-26 16:12

import encrypted_model_fields.fields
from django.db import migrations


def _reencrypt(apps, schema_editor):
    # Após o AlterField, linhas antigas contêm plaintext. Ler devolve o texto cru
    # (decrypt falha -> passthrough); save() regrava cifrado em repouso.
    Config = apps.get_model('integrations_sap_b1', 'SapB1IntegrationConfig')
    for cfg in Config.objects.all():
        if cfg.password:
            cfg.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_sap_b1', '0002_rename_sap_b1_bind_local_idx_integration_entity__6047cd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapb1integrationconfig',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.RunPython(_reencrypt, migrations.RunPython.noop),
    ]
