# Generated by Django 5.2 on 2026-06-29 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_sap_b1', '0004_sapb1integrationconfig_auto_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapB1ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_doc_entry', models.CharField(blank=True, max_length=100)),
                ('sap_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_log', to='integrations_sap_b1.sapb1syncrun')),
            ],
            options={
                'verbose_name': 'SAP B1 Export Log',
                'verbose_name_plural': 'SAP B1 Export Logs',
                'indexes': [models.Index(fields=['sap_status'], name='integration_sap_sta_987c2c_idx')],
            },
        ),
    ]
