# Generated by Django 5.2 on 2026-06-05 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostDiscoverySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('top_down', 'Seed top-down'), ('back_solve', 'Calibração (back-solve)')], max_length=20)),
                ('reference_inputs', models.JSONField(blank=True, default=dict)),
                ('reference_known_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('solved_fator_mo', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('achieved_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('error_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
