# Generated by Django 5.2 on 2026-06-05 12:25

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(db_index=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('densidade_kg_mm3', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('norma', models.CharField(blank=True, max_length=50)),
                ('forma_padrao', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sigla'],
                'constraints': [models.UniqueConstraint(fields=('sigla',), name='uniq_material_sigla')],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('chapa', 'Chapa'), ('tubo', 'Tubo'), ('barra', 'Barra'), ('forjado', 'Forjado'), ('fundido', 'Fundido')], max_length=20)),
                ('preco_brl_kg', encrypted_model_fields.fields.EncryptedCharField()),
                ('fornecedor', models.CharField(blank=True, max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='materials.material')),
            ],
            options={
                'indexes': [models.Index(fields=['material', 'forma', 'valid_from'], name='materials_m_materia_2425cd_idx')],
            },
        ),
    ]
