# Generated by Django 5.2 on 2026-06-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigaMetalurgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('nome', models.CharField(max_length=100)),
                ('familia', models.CharField(blank=True, max_length=60)),
                ('spec', models.CharField(blank=True, max_length=60)),
                ('s_curva', models.JSONField(blank=True, default=dict)),
                ('liga_fator', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('densidade_kg_mm3', models.DecimalField(decimal_places=10, default=0, max_digits=12)),
                ('preco_fator', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('temp_limite_c', models.IntegerField(default=370)),
                ('norma', models.CharField(blank=True, max_length=60)),
                ('edicao', models.CharField(blank=True, max_length=10)),
                ('tabela', models.CharField(blank=True, max_length=10)),
                ('linha', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['ordem', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='uniq_liga_codigo')],
            },
        ),
    ]
