# Generated by Django 5.2 on 2026-07-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_ligametalurgica'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(choices=[('aco_carbono', 'Aço Carbono'), ('inox_304L', 'Inox 304L'), ('inox_316L', 'Inox 316L'), ('geral', 'Geral (independe de liga)')], db_index=True, max_length=20)),
                ('componente', models.CharField(choices=[('chapas_pressao', 'Chapas de pressão'), ('tubos_troca', 'Tubos de troca'), ('tubos_bocais', 'Tubos de bocais'), ('forjados_flanges', 'Forjados/Flanges'), ('barras_chicanas', 'Barras/Chicanas'), ('estojos_prisioneiros', 'Estojos/Prisioneiros'), ('porcas', 'Porcas'), ('junta_cabecote', 'Junta de cabeçote')], db_index=True, max_length=20)),
                ('norma_astm', models.CharField(max_length=120)),
                ('condicao', models.CharField(blank=True, max_length=255)),
                ('certificacao', models.CharField(default='EN 10204 3.1', max_length=60)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['familia', 'componente'],
                'constraints': [models.UniqueConstraint(fields=('familia', 'componente'), name='uniq_material_standard')],
            },
        ),
    ]
