# Generated by Django 5.2 on 2026-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_part', models.CharField(choices=[('front_head', 'Cabeçote Frontal'), ('shell', 'Casco'), ('rear_head', 'Cabeçote Traseiro'), ('tube_bundle', 'Feixe Tubular'), ('tubesheet', 'Espelho'), ('baffle', 'Chicana'), ('tie_rod', 'Tirante'), ('nozzle', 'Bocal'), ('flange', 'Flange')], db_index=True, max_length=20)),
                ('tema_letter', models.CharField(blank=True, max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('standard_ref', models.CharField(blank=True, max_length=120)),
                ('parameter_schema', models.JSONField(blank=True, default=dict)),
                ('default_operations', models.JSONField(blank=True, default=list)),
                ('default_ndt', models.JSONField(blank=True, default=list)),
                ('is_global', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tema_part', 'tema_letter', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tema_part', 'tema_letter', 'name'), name='uniq_tema_template')],
            },
        ),
    ]
