# Generated by Django 5.2 on 2026-07-14 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tema_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_op', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('operacao', models.CharField(max_length=100)),
                ('metodo', models.CharField(blank=True, choices=[('radial', 'Radial'), ('cnc', 'CNC'), ('manual', 'Manual')], max_length=20)),
                ('driver', models.CharField(choices=[('diametro_bocal', 'Ø bocal'), ('n_furos', 'Nº furos'), ('n_tubos', 'Nº tubos'), ('comprimento', 'Comprimento'), ('diametro_casco', 'Ø casco'), ('area_solda', 'Área de solda'), ('massa', 'Massa'), ('volume', 'Volume'), ('fixo', 'Fixo')], max_length=20)),
                ('setup_fixo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('aplicavel_default', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_operations', to='tema_templates.componenttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'codigo_op'],
            },
        ),
    ]
