# Generated by Django 5.2 on 2026-06-05 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('orcamentista', 'Orçamentista'), ('engenheiro', 'Engenheiro'), ('gestor_comercial', 'Gestor Comercial'), ('admin', 'Admin')], db_index=True, default='orcamentista', max_length=20)),
                ('crea_number', models.CharField(blank=True, max_length=30)),
                ('crea_state', models.CharField(blank=True, max_length=2)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('role', 'engenheiro'), _negated=True), models.Q(('crea_number', ''), _negated=True), _connector='OR'), name='engenheiro_requires_crea')],
            },
        ),
    ]
