# Generated by Django 5.2 on 2026-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('orcamentista', 'Orçamentista'), ('engenheiro', 'Engenheiro'), ('gestor_comercial', 'Gestor Comercial'), ('admin', 'Admin')], db_index=True, default='orcamentista', max_length=20),
        ),
    ]
