# Generated by Django 5.2 on 2026-07-18 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('requires_crea', models.BooleanField(default=False)),
                ('is_admin_like', models.BooleanField(default=False)),
                ('is_seeded', models.BooleanField(default=False)),
                ('source_template', models.CharField(blank=True, max_length=64)),
                ('template_version', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'papel',
                'verbose_name_plural': 'papéis',
                'ordering': ['key'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='engenheiro_requires_crea',
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
