# Generated by Django 5.2 on 2026-06-25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OmieIntegrationConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="omie", max_length=20, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("app_key", models.CharField(blank=True, max_length=255)),
                ("app_secret", models.CharField(blank=True, max_length=255)),
                ("company_code", models.CharField(blank=True, max_length=50)),
                ("environment", models.CharField(blank=True, max_length=50)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("emit_on_of_completed", models.BooleanField(default=True)),
                ("fiscal_defaults", models.JSONField(blank=True, default=dict)),
                ("last_healthcheck_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuracao Omie",
                "verbose_name_plural": "Configuracoes Omie",
            },
        ),
        migrations.CreateModel(
            name="OmieFiscalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("ready", "Ready"), ("issued", "Issued"), ("failed", "Failed")], default="pending", max_length=20)),
                ("remote_document_id", models.CharField(blank=True, max_length=100)),
                ("remote_number", models.CharField(blank=True, max_length=100)),
                ("fiscal_defaults_snapshot", models.JSONField(blank=True, default=dict)),
                ("source_snapshot", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("config", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fiscal_documents", to="integrations_omie.omieintegrationconfig")),
                ("of", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="omie_fiscal_document", to="production.ordemfabricacao")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="integratio_status_42a529_idx"),
                    models.Index(fields=["remote_document_id"], name="integratio_remote_d_8f3eaa_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OmieInvoiceRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("success", "Success"), ("failed", "Failed"), ("skipped", "Skipped")], default="pending", max_length=20)),
                ("trigger", models.CharField(default="manual", max_length=30)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("config", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoice_runs", to="integrations_omie.omieintegrationconfig")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoice_runs", to="integrations_omie.omiefiscaldocument")),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["status", "started_at"], name="integratio_status_5f9d82_idx"),
                    models.Index(fields=["document", "status"], name="integratio_document_54fbc0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OmieInvoiceAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveSmallIntegerField()),
                ("status", models.CharField(choices=[("success", "Success"), ("failed", "Failed")], max_length=20)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="integrations_omie.omieinvoicerun")),
            ],
            options={
                "ordering": ["sequence", "created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "sequence"), name="uniq_omie_attempt_sequence"),
                ],
            },
        ),
    ]
