# Generated by Django 5.2 on 2026-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_omie', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='omiefiscaldocument',
            new_name='integration_status_26e726_idx',
            old_name='integratio_status_42a529_idx',
        ),
        migrations.RenameIndex(
            model_name='omiefiscaldocument',
            new_name='integration_remote__d6de18_idx',
            old_name='integratio_remote_d_8f3eaa_idx',
        ),
        migrations.RenameIndex(
            model_name='omieinvoicerun',
            new_name='integration_status_2342b1_idx',
            old_name='integratio_status_5f9d82_idx',
        ),
        migrations.RenameIndex(
            model_name='omieinvoicerun',
            new_name='integration_documen_70947d_idx',
            old_name='integratio_document_54fbc0_idx',
        ),
        migrations.AlterField(
            model_name='omieintegrationconfig',
            name='provider',
            field=models.CharField(default='omie', editable=False, max_length=20, unique=True),
        ),
    ]
