# Generated by Django 5.2 on 2026-06-26 16:12

import encrypted_model_fields.fields
from django.db import migrations


def _reencrypt(apps, schema_editor):
    # Após o AlterField, linhas antigas contêm plaintext. Ler devolve o texto cru
    # (decrypt falha -> passthrough); save() regrava cifrado em repouso.
    Config = apps.get_model('integrations_omie', 'OmieIntegrationConfig')
    for cfg in Config.objects.all():
        if cfg.app_key or cfg.app_secret:
            cfg.save(update_fields=['app_key', 'app_secret'])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_omie', '0002_rename_integratio_status_42a529_idx_integration_status_26e726_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omieintegrationconfig',
            name='app_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='omieintegrationconfig',
            name='app_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.RunPython(_reencrypt, migrations.RunPython.noop),
    ]
