# Generated by Django 5.2 on 2026-06-05 13:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('revision', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=500)),
                ('scope', models.CharField(choices=[('tube_bundle', 'Feixe Tubular'), ('complete', 'Equipamento Completo')], default='tube_bundle', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em Revisão'), ('approved', 'Aprovada'), ('sent', 'Enviada'), ('won', 'Ganha'), ('lost', 'Perdida')], default='draft', max_length=20)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('fator_preco', models.DecimalField(decimal_places=5, default=Decimal('1.01377'), max_digits=8)),
                ('impostos_pct', models.DecimalField(decimal_places=3, default=Decimal('23.303'), max_digits=6)),
                ('custo_material', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_mo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('preco_sem_impostos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('preco_com_impostos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('peso_bruto_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_liquido_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='quotations.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('custo_material', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_mo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='quotations.quotation')),
            ],
            options={
                'ordering': ['sort_order', 'codigo_item'],
            },
        ),
        migrations.CreateModel(
            name='ItemOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_op', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=20)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('aplicavel', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='quotations.quotationitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_mp', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=50)),
                ('forma', models.CharField(max_length=20)),
                ('peso_bruto_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_liquido_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('preco_kgf', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='quotations.quotationitem')),
            ],
        ),
    ]
