# Generated by Django 5.2 on 2026-07-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_itemoperation_custo_direto_itemoperation_horas_hh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoperation',
            name='horas_hh_sugerida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='itemoperation',
            name='horas_hm_sugerida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='itemoperation',
            name='origem',
            field=models.CharField(choices=[('seed', 'Motor'), ('template', 'Template'), ('manual', 'Manual')], default='seed', max_length=10),
        ),
    ]
