# Generated by Django 5.2 on 2026-07-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_itemoperation_horas_hh_sugerida_and_more'),
        ('tema_templates', '0002_componentoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='scope',
            field=models.CharField(choices=[('tube_bundle', 'Feixe Tubular'), ('complete', 'Equipamento Completo'), ('parts', 'Peças de Reposição')], default='tube_bundle', max_length=20),
        ),
        migrations.CreateModel(
            name='QuotationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_letter', models.CharField(blank=True, max_length=1)),
                ('material_sigla', models.CharField(blank=True, max_length=50)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('incluso', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quotations.quotation')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tema_templates.componenttemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
