# Generated by Django 5.2 on 2026-07-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_alter_quotation_scope_quotationpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='avisos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
