# Generated by Django 5.2 on 2026-07-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quotation_avisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pricing_basis',
            field=models.CharField(choices=[('referencial', 'Referencial'), ('validado_custo', 'Validado por custo')], default='referencial', editable=False, max_length=20),
        ),
    ]
