# Generated by Django 5.2 on 2026-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quotation_pricing_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoperation',
            name='taxa_hora_hm_sugerida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemoperation',
            name='taxa_hora_sugerida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
