# Generated by Django 5.2 on 2026-07-28 09:48

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('formulario', 'Formulário externo'), ('manual', 'Digitada no sistema'), ('importada', 'Importada de arquivo')], default='manual', max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('respondente', models.CharField(blank=True, max_length=255)),
                ('mes_referencia', models.CharField(blank=True, help_text='AAAA-MM', max_length=7)),
                ('custo_pessoal_direto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('custo_pessoal_indireto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('custo_galpao', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('custo_maquinas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('custo_estrutura', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Já rateado pelo percentual aplicável', max_digits=14)),
                ('pessoas_produtivas', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Só quem fabrica; indiretos não vendem hora', max_digits=8)),
                ('jornada_semanal_h', models.DecimalField(decimal_places=2, default=Decimal('44'), max_digits=6)),
                ('semanas_mes', models.DecimalField(decimal_places=2, default=Decimal('4.33'), max_digits=5)),
                ('fator_pratico_pct', models.DecimalField(decimal_places=2, default=Decimal('82'), help_text='Quanto da jornada vira produção. Prática consolidada: 80–85%', max_digits=5)),
                ('horas_extras_mes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('rate_praticado', models.DecimalField(blank=True, decimal_places=4, help_text='R$/h de mão de obra que a empresa cobra hoje', max_digits=12, null=True)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Resposta crua, para recomputar se a fórmula mudar')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estrutura de custo',
                'verbose_name_plural': 'estruturas de custo',
                'ordering': ['-valid_from', '-id'],
                'constraints': [models.UniqueConstraint(fields=('valid_from',), name='unique_cost_structure_valid_from')],
            },
        ),
    ]
