# Generated by Django 5.2 on 2026-06-26 16:12

import encrypted_model_fields.fields
from django.db import migrations


def _reencrypt(apps, schema_editor):
    # Após o AlterField, linhas antigas contêm plaintext. Ler devolve o texto cru
    # (decrypt falha -> passthrough); save() regrava cifrado em repouso.
    Config = apps.get_model('integrations_protheus', 'ProtheusIntegrationConfig')
    for cfg in Config.objects.all():
        if cfg.password or cfg.token:
            cfg.save(update_fields=['password', 'token'])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_protheus', '0002_protheuscatalogstaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protheusintegrationconfig',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='protheusintegrationconfig',
            name='token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.RunPython(_reencrypt, migrations.RunPython.noop),
    ]
