# Generated by Django 5.2 on 2026-06-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_bling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlingExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_id', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], max_length=20)),
                ('bling_nfe_id', models.CharField(blank=True, default='', max_length=100)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Exportacao Bling',
                'verbose_name_plural': 'Logs de Exportacao Bling',
                'ordering': ['-created_at'],
            },
        ),
    ]
