# Generated by Django 5.2 on 2026-06-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_bling', '0002_blingexportlog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blingexportlog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('of_id',), name='unique_bling_export_success_per_of'),
        ),
    ]
