# Generated by Django 5.2 on 2026-07-17 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('required', models.BooleanField(default=True)),
                ('approver_capability', models.CharField(blank=True, max_length=64)),
                ('is_builtin', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estágio de aprovação',
                'verbose_name_plural': 'estágios de aprovação',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('orcamentista', 'Orçamentista'), ('engenheiro', 'Engenheiro'), ('gestor_comercial', 'Gestor Comercial'), ('admin', 'Admin')], db_index=True, max_length=20)),
                ('capability', models.CharField(db_index=True, max_length=64)),
                ('allowed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'permissão de papel',
                'verbose_name_plural': 'permissões de papel',
                'ordering': ['capability', 'role'],
                'unique_together': {('role', 'capability')},
            },
        ),
    ]
