# Generated by Django 5.2 on 2026-07-18 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_seed_v2_approval_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('of.convert', 'Conversão em OF')], default='of.convert', max_length=32, unique=True)),
                ('name', models.CharField(default='Conversão em Ordem de Fabricação', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('source_template', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fluxo de aprovação',
                'verbose_name_plural': 'fluxos de aprovação',
            },
        ),
        migrations.AddField(
            model_name='approvalstage',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='access.approvalworkflow'),
        ),
    ]
