# Generated by Django 5.2 on 2026-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_seed_default_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='self_approval_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
